### ISSUE TITLE
Config.diff() issue with `rsp` type

### ISSUE THREAD

**Issue by alexandrecorso** [Juniper/py-junos-eznc#1082]
I found a strange behaviour with Ansible, using PyEZ via Junos Module. 

```
ansible            2.10.0
junos-eznc     2.5.3
```

The module I use with ansible is this one:
```
juniper_junos_config:
        src: "{{ path_junos_conf }}"
        provider: "{{ credentials }}"
        config_mode: "private"
        load: replace
        ignore_warning: true
        diff: true
        check: true
        commit: false
```

On some devices - MX (Junos: 18.4R3-S5.4) I got an error on the modulee Config.diff
```
  File "/Users/acorso/.virtualenvs/ansible/lib/python3.8/site-packages/jnpr/junos/utils/config.py", line 256, in diff
    diff_txt = rsp.find("configuration-output").text
```

I check the value of `rsp` (via `return f"rsp: {type(rsp)}: {rsp}"` on the file https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/utils/config.py, just before the line 256)
```
"rsp: <class 'bool'>: True"
```

On `https://github.com/Juniper/py-junos-eznc/blob/master/lib/jnpr/junos/utils/config.py` I don't see any check about the type like 
```
if not type(rsp) == dict: 
    return None
```

I'm curious about the type of `rsp` variable. I should be something like this:
```
"rsp: <class 'lxml.etree._Element'>: <Element configuration-information at 0x112136680>"
```

I found this issue only on one device and where there is the no change (no diff)

Alexandre Corso
