### ISSUE TITLE
Lane information for ET interfaces

### ISSUE THREAD

**Issue by luckenbach** [Juniper/py-junos-eznc#1102]
I am attempting to extend the ask in #820 to create a more informative table via the following yaml but my 'lanes' value ends up empty.

```yaml
---
PhyPortDiagTable:
  rpc: get-interface-optics-diagnostics-information
  args:
    interface_name: '[efgx][et]-*'
  args_key: interface_name
  item: physical-interface
  view: PhyPortDiagView

PhyPortDiagView:
  groups:
    diag: optics-diagnostics
  fields_diag:
    rx_optic_power: rx-signal-avg-optical-power-dbm
    tx_optic_power: laser-output-power-dbm
    module_temperature: module-temperature
    module_voltage: module-voltage
    lanes: _LaneInfoTable

_LaneInfoTable:
  item: optics-diagnostics/optics-diagnostics-lane-values
  key: lane-index
  view: _LaneInfoView

_LaneInfoView:
  fields:
    tx_power : laser-output-power
    rx_power : laser-rx-optical-power
```

I have tried various things in the `_LaneInfoTable` item ranging from `physical-interface/optics-diagnostics/optics-diagnostics-lane-values` to just `optics-diagnostics-lane-values`
