### ISSUE TITLE
The JSON output in any Juniper Ansible module will not display our config due to a certain line in our standard configuration causing JSONLoadError(reason: Invalid  \\escape.....) 

### ISSUE THREAD

**Issue by Reidy10** [Juniper/py-junos-eznc#1111]
I have come across an issue where a line of Juniper configuration on any of our SRX devices seems to clash and fail with any Ansible or Junos module when asking to display output as JSON. Unfortunately, it's not a simple case of changing our SRX config as this is on over 800 devices in production.

The Config from the SRX in question causing an issue is the following in set format:
`set system syslog host 1.2.3.4 match "!(.*\(root\) CMD \((newsyslog|.*atrun)\).*)|.*throttled|.*%NTP-5"`

When it is removed the JSON output/display command from facts/config/command module works for that device. I guess there is a pattern in the match condition causing an error. We have a much shorter, more basic example in another syslog config that works:
`set system syslog file messages match "!(.*uspinfo*)"`

My Ansible setup is the following:
```
ansible 2.10.8
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/craig/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Apr  5 2021, 09:00:41) [GCC 6.3.0 `20170516]

/home/craig/.ansible/collections/ansible_collections
Collection     Version
-------------- -------
juniper.device 0.1.0  

Name: junos-eznc
Version: 2.6.0 
```

The testing device:
`Model: srx345
Junos: 18.2R3-S2.9`

The Playbook:
```
---
- name: Gather device facts
  hosts: juniper_srx345_lab
  connection: ansible.netcommon.netconf
  gather_facts: false
#  roles:
#    - Juniper.junos
  collections:
#    - junipernetworks.junos
    - juniper.device
  
  vars: 
    ansible_network_os: junipernetworks.junos.junos

  tasks:
#    - name: Gather useful output
#      junipernetworks.junos.junos_rpc:
#        rpc: get-configuration
#        output: json # not working

#    - name: Gather useful output
#      junipernetworks.junos.junos_command:
#        commands: show configuration
#        display: json # not working

    - name: Gather config output
      config:
        retrieve: committed
        format: "json" 
      register: host_vars_output
```

The output - cust002 does not have the line of config and it works, cust003 has the config and the JSON error is displayed ( I know I need to upgrade python):
```
`ok: [cust002]
fatal: [cust003]: FAILED! => {"changed": false, "module_stderr": "/usr/local/lib/python3.5/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.\n  from cryptography.hazmat.backends import default_backend\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.5/dist-packages/jnpr/junos/device.py\", line 878, in execute\n    return json.loads(rpc_rsp_e.text)\n  File \"/usr/lib/python3.5/json/__init__.py\", line 319, in loads\n    return _default_decoder.decode(s)\n  File \"/usr/lib/python3.5/json/decoder.py\", line 339, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"/usr/lib/python3.5/json/decoder.py\", line 355, in raw_decode\n    obj, end = self.scan_once(s, idx)\njson.decoder.JSONDecodeError: Invalid \\escape: line 161 column 36 (char 5920)\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/home/craig/.ansible/tmp/ansible-local-308037rqejc8b/ansible-tmp-1620296916.259649-30834-250674008858576/AnsiballZ_config.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/craig/.ansible/tmp/ansible-local-308037rqejc8b/ansible-tmp-1620296916.259649-30834-250674008858576/AnsiballZ_config.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/craig/.ansible/tmp/ansible-local-308037rqejc8b/ansible-tmp-1620296916.259649-30834-250674008858576/AnsiballZ_config.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.juniper.device.plugins.modules.config', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python3.5/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.5/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib/python3.5/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_config_payload_hcvqejb3/ansible_config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py\", line 1140, in <module>\n  File \"/tmp/ansible_config_payload_hcvqejb3/ansible_config_payload.zip/ansible_collections/juniper/device/plugins/modules/config.py\", line 1096, in main\n  File \"/tmp/ansible_config_payload_hcvqejb3/ansible_config_payload.zip/ansible_collections/juniper/device/plugins/module_utils/juniper_junos_common.py\", line 1461, in get_configuration\n  File \"/usr/local/lib/python3.5/dist-packages/jnpr/junos/rpcmeta.py\", line 152, in get_config\n    response = self._junos.execute(rpc, **kwargs)\n  File \"/usr/local/lib/python3.5/dist-packages/jnpr/junos/decorators.py\", line 76, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/lib/python3.5/dist-packages/jnpr/junos/decorators.py\", line 31, in wrapper\n    return function(*args, **kwargs)\n  File \"/usr/local/lib/python3.5/dist-packages/jnpr/junos/device.py\", line 884, in execute\n    raise JSONLoadError(ex, rpc_rsp_e.text)\njnpr.junos.exception.JSONLoadError: JSONLoadError(reason: Invalid \\escape: line 161 column 36 (char 5920), \nThe offending config appears to be: \n159:                     }\n160:                     ], \n161:                     \"match\" : \"!(.*\\(root\\) CMD \\((newsyslog|.*atrun)\\).*)|.*throttled|.*%NTP-5\", \n162:                     \"port\" : 514, \n163:                     \"facility-override\" : \"local4\", \n)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`
```
