### ISSUE TITLE
<junos_install_os> Reboot variable is not validated in the ansible playbook for image install.

### ISSUE THREAD

**Issue by mamathac** [Juniper/py-junos-eznc#218]
Model : SRX5600 standalone

Description: Despite of setting the Reboot variable to 'no', reboot happens post install. It overrides the value set at variable.

```
Playbook code -

---
- name: Junos OS
  hosts: all
  connection: local
  gather_facts: no
  vars:
    restart_wait_time: 3600
    reboot: 'no'

  tasks:
    - include: task_check_nc

    - name: install Junos OS package
      junos_install_os:
        host={{ inventory_hostname }}
        version=12.1X44-D10
        package=/usr/local/junos/images/junos-srx5000-12.1X44-D10-domestic.tgz
        logfile=/usr/local/junos/log/software.log
      register: sw
```

Log file:

2014-05-22 17:52:34,405:asthra:installing software ... please be patient ...
2014-05-22 17:54:16,471:asthra:<REBOOT>
2014-05-22 17:54:16,687:asthra:upgrade pending reboot cycle, please be patient.
2014-05-22 17:54:16,751:asthra:pausing: 10

From the junos_install_os help:

```

   reboot:
      description:
         - determines if a reboot is performed after the OS is loaded
      required: false
      default: yes
      choices: ['yes','no']
```

If the Value is set to 'no' should that not be considered.
