### ISSUE TITLE
Configuration Table Options cannot be set in YAML

### ISSUE THREAD

**Issue by shermdog** [Juniper/py-junos-eznc#387]
The options keyword is not properly being supported.  Currently the only working way it so specify during the get  `table.get(options={})`

Should be able to set things in the following manner

```yaml
ConfigTable:
    get: groups
    item:
    args_key: name
	options: {}
    view: ConfigView
```
or
```yaml
from jnpr.junos.jxml import INHERIT
ConfigTable:
    get: groups
    item:
    args_key: name
	options: INHERIT
    view: ConfigView
```
