### ISSUE TITLE
Built-in VlanTable does not define a valid key

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/py-junos-eznc#419]
vlan.yml file is currently:

```
---
VlanTable:
  rpc: get-vlan-information
  item: vlan
  view: VlanView

VlanView:
  fields:
    instance: vlan-instance
    name: vlan-name
    created: vlan-create-time
    status: vlan-status
    owner: vlan-owner
    tag: vlan-tag
    members: .//vlan-member-interface
```

The XML output is:
```
{master:0}
regress@jcex4> show vlans | display xml    
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1D0/junos">
    <vlan-information xmlns="http://xml.juniper.net/junos/15.1D0/junos-esw" junos:style="terse">
        <vlan-terse/>
        <vlan>
            <vlan-instance>0</vlan-instance>
            <vlan-name>bar</vlan-name>
            <vlan-create-time>Fri Jun 19 00:32:22 2015
            </vlan-create-time>
            <vlan-status>Enabled</vlan-status>
            <vlan-owner>static</vlan-owner>
            <vlan-tag>5</vlan-tag>
            <vlan-tag-string>5</vlan-tag-string>
            <vlan-index>5</vlan-index>
            <vlan-protocol-port>Port Mode</vlan-protocol-port>
            <vlan-detail>
                <vlan-member-list>
                    <vlan-member>
                        <vlan-member-interface>None</vlan-member-interface>
                    </vlan-member>
                </vlan-member-list>
            </vlan-detail>
        </vlan>
        <vlan>
            <vlan-instance>0</vlan-instance>
            <vlan-name>default</vlan-name>
            <vlan-create-time>Sat Feb  7 11:36:19 2015
            </vlan-create-time>
            <vlan-status>Enabled</vlan-status>
            <vlan-owner>static</vlan-owner>
            <vlan-tag>0</vlan-tag>
            <vlan-index>2</vlan-index>
            <vlan-protocol-port>Port Mode</vlan-protocol-port>
            <vlan-detail>
                <vlan-member-list>
                    <vlan-member>
                        <vlan-member-interface>None</vlan-member-interface>
                    </vlan-member>
                </vlan-member-list>
            </vlan-detail>
        </vlan>                         
        <vlan>
            <vlan-instance>0</vlan-instance>
            <vlan-name>foo</vlan-name>
            <vlan-create-time>Fri Jun 19 00:28:54 2015
            </vlan-create-time>
            <vlan-status>Enabled</vlan-status>
            <vlan-owner>static</vlan-owner>
            <vlan-tag>6</vlan-tag>
            <vlan-tag-string>6</vlan-tag-string>
            <vlan-index>3</vlan-index>
            <vlan-protocol-port>Port Mode</vlan-protocol-port>
            <vlan-detail>
                <vlan-member-list>
                    <vlan-member>
                        <vlan-member-interface>None</vlan-member-interface>
                    </vlan-member>
                </vlan-member-list>
            </vlan-detail>
        </vlan>
    </vlan-information>
    <cli>
        <banner>{master:0}</banner>
    </cli>
</rpc-reply>

{master:0}
regress@jcex4> 
```

A key field needs to be defined for VlanTable in vlan.yml.
The key could be either vlan-tag or vlan-name depending on whether you prefer the table to be keyed by vlan name or vlan id.
```
---
VlanTable:
  rpc: get-vlan-information
  item: vlan
  key: vlan-tag  # Alternatively could be: key: vlan-name
  view: VlanView

VlanView:
  fields:
    instance: vlan-instance
    name: vlan-name
    created: vlan-create-time
    status: vlan-status
    owner: vlan-owner
    tag: vlan-tag
    members: .//vlan-member-interface
```
