### ISSUE TITLE
The name of a View() attribute can not also be used as a field name in a View's YAML file.

### ISSUE THREAD

**Issue by stacywsmith** [Juniper/py-junos-eznc#423]
If you attempt to use the name of a View() attribute as a field name in a View's YAML file, the View() attribute takes precedence and the field name is not accessible.

For an example/discussion of this, see:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/junos-python-ez/8X0LmP_15fU/AztUGvKQDAAJ

```
This condition exists in the included VlanView in the vlan.yml file.

I suggest changing this:

VlanView:
  fields:
    instance: vlan-instance
    name: vlan-name 
    created: vlan-create-time
    status: vlan-status
    owner: vlan-owner
    tag: vlan-tag
    members: .//vlan-member-interface

to:

VlanView:
  fields:
    instance: vlan-instance
    vlan_name: vlan-name 
    created: vlan-create-time
    status: vlan-status
    owner: vlan-owner
    tag: vlan-tag
    members: .//vlan-member-interface


A similar condition also exists in _BfdSessionClientView in the bfd.yml file.

I suggest changing this:

_BfdSessionClientView:
  fields:
    name: client-name
    transmission_interval: client-transmission-interval
    reception_interval: client-reception-interval

to:

_BfdSessionClientView:
  fields:
    client_name: client-name
    transmission_interval: client-transmission-interval
    reception_interval: client-reception-interval
```
