### ISSUE TITLE
pyez rpc request bug

### ISSUE THREAD

**Issue by inetman** [Juniper/py-junos-eznc#470]
Hello, 
We are trying request RPC command and recieved reply form juniper devices:
```
root@srx-R1# run show route advertising-protocol bgp 192.168.1.1

inet.0: 570101 destinations, 570101 routes (10 active, 0 holddown, 570091 hidden)
  Prefix          Nexthop           MED     Lclpref    AS path
* 10.30.0.0/23            Self                                    64700 64700 I
```
```
r.volodin@srx-R1# run show route advertising-protocol bgp 192.168.1.1 | display xml rpc 
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos">
    <rpc>
        <get-route-information>
                <bgp/>
                <neighbor>192.168.1.1</neighbor>
        </get-route-information>
    </rpc>
    <cli>
        <banner>[edit routing-options]</banner>
    </cli>
</rpc-reply>
```
YAML
``` 
bgpNeighborTable:
 rpc: get-route-information
 args:
  bgp: true
  extensive: True
 item: route-table/rt
 key: rt-destination
 view: bgpView

bgpView:
 fields:
  as-path: rt-entry/as-path
  rt_destination: rt-destination
  rt_prefix_length: rt-prefix-length
  preference: rt-entry/preference
  community: communities/community
```

YAML as DICT
```
{'bgpNeighborTable': {'item': 'route-table/rt', 'rpc': 'get-route-information', 'args': {'bgp': True}, 'key': 'rt-destination', 'view': 'bgpView'}, 'bgpView': {'fields': {'as-path': 'rt-entry/as-path', 'rt_prefix_length': 'rt-prefix-length', 'rt_destination': 'rt-destination', 'community': 'communities/community', 'preference': 'rt-entry/preference'}}}
```

but we are received RPC error below:
```
jnpr.junos.exception.RpcError: RpcError(severity: error, bad_element: bgp, message: syntax error, expecting <invoke-on>)
```
We think that it is bug.

**Comment by inetman** [comment]
netconf traceoptions:
r.volodin@srx-R1> show log netconf | no-more    
Dec 24 11:34:35 [4957] Outgoing: </configuration-information>
Dec 24 11:34:35 [4957] Outgoing: </rpc-reply>
Dec 24 11:34:35 [4957] Outgoing: ]]>]]>
Dec 24 11:34:55 [4957] Incoming: <?xml version="1.0" encoding="UTF-8"?><nc:rpc xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:c3a95ea6-aa10-11e5-80ee-bcee7b9f1ec6"><get-route-information><bgp/><extensive/><destination>10.30.0.0/23</destination><neighbor>192.168.1.1</neighbor></get-route-information></nc:rpc>]]>]]>
Dec 24 11:34:55 [4957] Outgoing: <rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns:junos="http://xml.juniper.net/junos/15.1X49/junos" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="urn:uuid:c3a95ea6-aa10-11e5-80ee-bcee7b9f1ec6">
Dec 24 11:34:55 [4957] Outgoing: <rpc-error>
Dec 24 11:34:55 [4957] Outgoing: <error-type>protocol</error-type>
Dec 24 11:34:55 [4957] Outgoing: <error-tag>operation-failed</error-tag>
Dec 24 11:34:55 [4957] Outgoing: <error-severity>error</error-severity>
Dec 24 11:34:55 [4957] Outgoing: <error-message>syntax error, expecting &lt;invoke-on&gt;</error-message>
Dec 24 11:34:55 [4957] Outgoing: <error-info>
Dec 24 11:34:55 [4957] Outgoing: <bad-element>bgp</bad-element>
Dec 24 11:34:55 [4957] Outgoing: </error-info>
Dec 24 11:34:55 [4957] Outgoing: </rpc-error>
Dec 24 11:34:55 [4957] Outgoing: </rpc-reply>
Dec 24 11:34:55 [4957] Outgoing: ]]>]]>
Dec 24 11:34:56 [4957] Outgoing:

**Comment by ganeshnalawade** [comment]
@inetman

This is a known issue, as a workaround please use below rpc as reference
```
<rpc>
     <get-route-information>
             <advertising-protocol-name>bgp</advertising-protocol-name>
             <neighbor>192.168.1.1</neighbor>
     </get-route-information>
 </rpc>
```

YAML  can be modified as below
```
bgpNeighborTable:
 rpc: get-route-information
 args:
  extensive: True
  advertising-protocol-name: bgp
 args_key: neighbor
 item: route-table/rt
 key: rt-destination
 view: bgpView

bgpView:
 fields:
  as-path: rt-entry/as-path
  rt_destination: rt-destination
  rt_prefix_length: rt-prefix-length
  preference: rt-entry/preference
  community: communities/community
```

Please let me know if it works for you.
