### ISSUE TITLE
Retrieve detailed view of LLDP neighbors

### ISSUE THREAD

**Issue by mirceaulinic** [Juniper/py-junos-eznc#474]
I am trying to retrieve a detailed view of the LLDP neighbors.

From the CLI there is no 'detail' parameter available and in order to retrieve more information it is necessary to execute separate commands for each and every neighbor. Moreover, the RPCs are different:

```# show lldp neighbors``` will return a list of neighbors, for instance:

```
Local Interface    Parent Interface    Chassis Id          Port info          System Name
xe-0/1/1           ae7                 00:1c:73:ee:c0:46   Ethernet3/29/1     core01.sjc01
xe-0/3/3           ae7                 00:1c:73:ee:c0:46   Ethernet3/29/2     core01.sjc01
xe-2/0/5           ae7                 00:1c:73:ee:c0:46   Ethernet3/29/3     core01.sjc01
xe-2/1/5           ae7                 00:1c:73:ee:c0:46   Ethernet3/29/4     core01.sjc01
```

To this command corresponds RPC **get-lldp-neighbors-information**.

In order to get a detailed view it is necessary to execute a second command ```show lldp neighbors interface xe-0/1/1```.  For this command, the available RPC is **get-lldp-interface-neighbors**.

In that case, is there any possibility to retrieve the details of all LLDP neighbors in one single request?

```
junos_lldp_neighbors_detail_table:
  rpc: get-lldp-neighbors-information
  item: lldp-neighbor-information
  key: lldp-local-port-id
  view: junos_lldp_neighbors_detail_view

junos_lldp_neighbors_detail_view:
  fields:
    interface: lldp-local-port-id
    parent_interface: lldp-local-parent-interface-name
    remote_port: lldp-remote-port-id
    remote_chassis_id: lldp-remote-chassis-id
    remote_port: lldp-remote-port-id
    remote_port_description: lldp-remote-port-description
    remote_system_name: lldp-remote-system-name
    remote_system_description: lldp-system-description/lldp-remote-system-description
    remote_system_capab: lldp-remote-system-capabilities-supported
    remote_system_enable_capab: lldp-remote-system-capabilities-enabled
```

Returns None for all fields belonging to the detailed view (remote_system_description, remote_system_capab etc).
