### ISSUE TITLE
markupsafe missing as requirement

### ISSUE THREAD

**Issue by dgarros** [Juniper/py-junos-eznc#611]
Hi 

I just installed pyez on a new ubuntu server and the library `markupsafe` was missing
I checked the requirement file and it's not listed there

After `sudo pip install markupsafe` it was working fine

Thks
Damien

**Comment by stacywsmith** [comment]
@dgarros I don't see MarkupSafe as a direct requirement in PyEZ. I do see that it is an indirect requirement via Jinja2. However, I also see that MarkupSafe is listed as a dependency of Jinja2:
https://github.com/pallets/jinja/blob/master/setup.py#L72

So, I'm not quite sure why it was missing on your new install. Do you have any logs of the problem we could look at?

**Comment by dgarros** [comment]
Insteresting, I installed pyez on a unbuntu server using the Ansible Pip module

```
  - name: Install Libraries with PIP
    pip: name={{ item }}
    with_items:
      - junos-eznc
      - lxml
      - jxmlease
      - ansible
```

Later I tried to load pyez using python shell and I got the error message related to `MarkupSafe` missing ...

this is surprising ..
