### ISSUE TITLE
Empty bgp-rib in bgp-peer causing traceback in jnpr/junos/factory/view.py

### ISSUE THREAD

**Issue by rucarrol** [Juniper/py-junos-eznc#770]
Hey,

So I'm not 100% sure on how to solve this. 

Given a table definition:

```
---
bgpTable:
 rpc: get-bgp-neighbor-information
 item: bgp-peer
 view: bgpView
 key: peer-id

bgpView:
 fields:
  local_as: local-as
  peer_as: peer-as
  local_address: local-address
  peer_id: peer-id
  local_id: local-id
  route_received: bgp-rib/received-prefix-count
  route_accepted: bgp-rib/accepted-prefix-count
  state: peer-state
```

It works pretty ok, however we do have a few peers which reply with an XML envelope as follows (peer-as changed):

```
        <bgp-peer junos:style="terse">
            <peer-address>10.250.6.4</peer-address>
            <peer-as>23456</peer-as>
            <input-messages>0</input-messages>
            <output-messages>0</output-messages>
            <route-queue-count>0</route-queue-count>
            <flap-count>0</flap-count>
            <elapsed-time junos:seconds="2618224">4w2d 7:17:04</elapsed-time>
            <description>Lab MX-1</description>
            <peer-state>Active</peer-state>
        </bgp-peer>
```
We notice that this peer does not return `<bgp-rib junos:style="terse">`. 

Due to this, we bail out here: 

```
  File "<removed>/Python/2.7/lib/python/site-packages/jnpr/junos/factory/view.py", line 207, in __repr__
    print("self.name: %s" %  self.name)
  File "<removed>/Python/2.7/lib/python/site-packages/jnpr/junos/factory/view.py", line 218, in __getattr__
    raise ValueError("Unknown field: '%s'" % name)
```

What's happening is that we're hitting this piece of code: 

```
    def __getattr__(self, name):
        """
        returns a view item value, called as :obj.name:
        """
        item = self.FIELDS.get(name)
        if item is None:
            raise ValueError("Unknown field: '%s'" % name)
```

`name` in this case, is `None` (Due to lack of bgp-rib entry), so we throw an exception. This causes the function to_json() to fail (However we can try/except around this). 

I'm not sure that this is expected use-case. Expectation from my side is that we either soft-fail, or return empty dict for this peer's table, since the peer exists, but it's got no RIB associated with it.

Said peer's config is similar to this:
```
set protocols bgp group EXAMPLE_BGP_GROUP neighbor 10.250.6.4 import REJECT-ALL
set protocols bgp group EXAMPLE_BGP_GROUP neighbor 10.250.6.4 family inet unicast prefix-limit maximum 1
set protocols bgp group EXAMPLE_BGP_GROUP neighbor 10.250.6.4 family inet unicast prefix-limit teardown idle-timeout forever
```

Should be re-producable. 

Cheers
/Ruairi
